# Generated by Django 4.2 on 2024-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('Горячие блюда', 'Горячие блюда'), ('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Супы', 'Супы'), ('Выпечка', 'Выпечка'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
